spring.application.name=backend
# Server
server.port=5000

# MongoDB
spring.data.mongodb.uri=mongodb+srv://ht934715:1234@cluster0.kzg9o.mongodb.net/Backend?retryWrites=true&w=majority

# Redis
# spring.data.redis.host=aptimaster-njkhw7.serverless.use1.cache.amazonaws.com
# spring.data.redis.port=6379
# spring.data.redis.ssl.enabled=true

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false

# JWT
jwt.secret=jcjcswubcsgwbcbbwjbschwbsbcbbebecce
jwt.expiration=604800000

# Phone
phone.secret=1234567890123456
#Sens otp
ninzasms.api.url=https://ninzasms.in.net/auth/send_sms
ninzasms.api.key=NINZASMSb933c7ba9ff2e6f0bfb7cdd953fe4f8f0df02f886a9fd3405a56
ninzasms.sender.id=15723